<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3cd08675-df73-49a6-bdba-3e7b253782eb</testSuiteGuid>
   <testCaseLink>
      <guid>db131f17-306f-4873-80f9-53a0b2f854b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Manual/TC Login/TC Success Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0dcf33b-b91a-4228-a438-5f084837b24d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ac44f8-f263-44e9-8ba0-d4a8e5ddec07</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b3521f05-e2e7-42ad-b1ff-ff11a1df0a1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Manual/TC Login/TC Failed Login With Invalid Username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3e3c2a7-23fa-43e5-b210-10b1580c5de3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bed7310-3c2e-4102-b888-a44cc400b23c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ace18d1c-0e74-4140-aa91-9f36d8e9607a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Manual/TC Login/TC Failed Login With Invalid Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>120272eb-db08-405c-b618-4d6e7642e964</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2837abcf-1aca-4dd6-a93a-55972c128bfc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
